spring:
  thymeleaf:
    enabled: false
    cache: false

  datasource:
    url: jdbc:mysql://192.168.222.10:3307/yuyu-common-web?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    #redis
  redis:
    host: 192.168.222.133
    port: 6379
    max-wait: 30000
    max-active: 100
    max-idle: 20
    min-idle: 0
    timeout: 3000
    password: redis

server:
  port: 8001

  tomcat:
    uri-encoding: utf-8

mybatis:
  mapper-locations: mapper/**/*Mapper.xml





